In [22]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression

In [23]:
flange30 = pd.read_csv('data/flange_30.csv')
flange30

,Platform_Area,Topside_LWT,Lifetime,Shipbuilding_Time,Oil_Production,Block,Process,Flange_Total,Flange_usage
0,19308.20,7000,15,1.8,0.120,99,90,784,9
1,18037.60,20000,20,3.2,0.035,112,91,981,17
2,20021.60,6500,17,1.9,0.100,103,91,771,10
3,17852.80,14500,20,3.0,0.180,119,89,918,12
4,19825.00,32000,30,3.6,0.220,90,88,1076,14
5,18605.00,37478,20,3.7,0.220,120,88,1109,10
6,19842.99,14000,15,2.3,0.140,106,92,911,16
7,14927.00,16000,17,2.2,0.085,108,89,937,7
8,12498.20,12000,15,2.1,0.080,106,89,882,15
9,10176.60,4500,10,1.9,0.060,85,89,708,11

In [24]:
x_flange30 = flange30.drop(columns = ['Flange_usage'])
x_flange30

,Platform_Area,Topside_LWT,Lifetime,Shipbuilding_Time,Oil_Production,Block,Process,Flange_Total
0,19308.20,7000,15,1.8,0.120,99,90,784
1,18037.60,20000,20,3.2,0.035,112,91,981
2,20021.60,6500,17,1.9,0.100,103,91,771
3,17852.80,14500,20,3.0,0.180,119,89,918
4,19825.00,32000,30,3.6,0.220,90,88,1076
5,18605.00,37478,20,3.7,0.220,120,88,1109
6,19842.99,14000,15,2.3,0.140,106,92,911
7,14927.00,16000,17,2.2,0.085,108,89,937
8,12498.20,12000,15,2.1,0.080,106,89,882
9,10176.60,4500,10,1.9,0.060,85,89,708

In [25]:
y_flange30 = pd.DataFrame(flange30, columns=['Flange_usage'])
y_flange30

   Flange_usage
0             9
1            17
2            10
3            12
4            14
5            10
6            16
7             7
8            15
9            11

In [26]:
linear_regressor = LinearRegression()
linear_regressor.fit(x_flange30,y_flange30)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [27]:
print(linear_regressor.coef_)
print(linear_regressor.intercept_)

[[-1.18990657e-03 -1.72410476e-04  3.72186989e-01  3.59070083e+00
   2.70967521e+01 -5.18503722e-02  3.62219745e+00  1.12626990e-02]]
[-313.30251209]

In [60]:
polynomial_features = PolynomialFeatures(degree = 3, interaction_only = False, include_bias=False)
poly_regressor = LinearRegression()
pipeline = Pipeline([("polynomial_features",polynomial_features),("linear_regression",poly_regressor)])
pipeline.fit(x_flange30,y_flange30)

Pipeline(memory=None,
     steps=[('polynomial_features', PolynomialFeatures(degree=3, include_bias=False, interaction_only=False)), ('linear_regression', LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False))])

In [61]:
polynomial_features.get_feature_names()

['x0',
 'x1',
 'x2',
 'x3',
 'x4',
 'x5',
 'x6',
 'x7',
 'x0^2',
 'x0 x1',
 'x0 x2',
 'x0 x3',
 'x0 x4',
 'x0 x5',
 'x0 x6',
 'x0 x7',
 'x1^2',
 'x1 x2',
 'x1 x3',
 'x1 x4',
 'x1 x5',
 'x1 x6',
 'x1 x7',
 'x2^2',
 'x2 x3',
 'x2 x4',
 'x2 x5',
 'x2 x6',
 'x2 x7',
 'x3^2',
 'x3 x4',
 'x3 x5',
 'x3 x6',
 'x3 x7',
 'x4^2',
 'x4 x5',
 'x4 x6',
 'x4 x7',
 'x5^2',
 'x5 x6',
 'x5 x7',
 'x6^2',
 'x6 x7',
 'x7^2',
 'x0^3',
 'x0^2 x1',
 'x0^2 x2',
 'x0^2 x3',
 'x0^2 x4',
 'x0^2 x5',
 'x0^2 x6',
 'x0^2 x7',
 'x0 x1^2',
 'x0 x1 x2',
 'x0 x1 x3',
 'x0 x1 x4',
 'x0 x1 x5',
 'x0 x1 x6',
 'x0 x1 x7',
 'x0 x2^2',
 'x0 x2 x3',
 'x0 x2 x4',
 'x0 x2 x5',
 'x0 x2 x6',
 'x0 x2 x7',
 'x0 x3^2',
 'x0 x3 x4',
 'x0 x3 x5',
 'x0 x3 x6',
 'x0 x3 x7',
 'x0 x4^2',
 'x0 x4 x5',
 'x0 x4 x6',
 'x0 x4 x7',
 'x0 x5^2',
 'x0 x5 x6',
 'x0 x5 x7',
 'x0 x6^2',
 'x0 x6 x7',
 'x0 x7^2',
 'x1^3',
 'x1^2 x2',
 'x1^2 x3',
 'x1^2 x4',
 'x1^2 x5',
 'x1^2 x6',
 'x1^2 x7',
 'x1 x2^2',
 'x1 x2 x3',
 'x1 x2 x4',
 'x1 x2 x5',
 'x1 x2 x6',
 'x1 x2 x7',
 'x1 x3^2',
 'x1 x3 x4',
 'x1 x3 x5',
 'x1 x3 x6',
 'x1 x3 x7',
 'x1 x4^2',
 'x1 x4 x5',
 'x1 x4 x6',
 'x1 x4 x7',
 'x1 x5^2',
 'x1 x5 x6',
 'x1 x5 x7',
 'x1 x6^2',
 'x1 x6 x7',
 'x1 x7^2',
 'x2^3',
 'x2^2 x3',
 'x2^2 x4',
 'x2^2 x5',
 'x2^2 x6',
 'x2^2 x7',
 'x2 x3^2',
 'x2 x3 x4',
 'x2 x3 x5',
 'x2 x3 x6',
 'x2 x3 x7',
 'x2 x4^2',
 'x2 x4 x5',
 'x2 x4 x6',
 'x2 x4 x7',
 'x2 x5^2',
 'x2 x5 x6',
 'x2 x5 x7',
 'x2 x6^2',
 'x2 x6 x7',
 'x2 x7^2',
 'x3^3',
 'x3^2 x4',
 'x3^2 x5',
 'x3^2 x6',
 'x3^2 x7',
 'x3 x4^2',
 'x3 x4 x5',
 'x3 x4 x6',
 'x3 x4 x7',
 'x3 x5^2',
 'x3 x5 x6',
 'x3 x5 x7',
 'x3 x6^2',
 'x3 x6 x7',
 'x3 x7^2',
 'x4^3',
 'x4^2 x5',
 'x4^2 x6',
 'x4^2 x7',
 'x4 x5^2',
 'x4 x5 x6',
 'x4 x5 x7',
 'x4 x6^2',
 'x4 x6 x7',
 'x4 x7^2',
 'x5^3',
 'x5^2 x6',
 'x5^2 x7',
 'x5 x6^2',
 'x5 x6 x7',
 'x5 x7^2',
 'x6^3',
 'x6^2 x7',
 'x6 x7^2',
 'x7^3']

In [62]:
features = pd.DataFrame(polynomial_features.transform(x_flange30), columns=polynomial_features.get_feature_names(x_flange30.columns))
print(features)

   Platform_Area  Topside_LWT  Lifetime  Shipbuilding_Time  Oil_Production  \
0       19308.20       7000.0      15.0                1.8           0.120
1       18037.60      20000.0      20.0                3.2           0.035
2       20021.60       6500.0      17.0                1.9           0.100
3       17852.80      14500.0      20.0                3.0           0.180
4       19825.00      32000.0      30.0                3.6           0.220
5       18605.00      37478.0      20.0                3.7           0.220
6       19842.99      14000.0      15.0                2.3           0.140
7       14927.00      16000.0      17.0                2.2           0.085
8       12498.20      12000.0      15.0                2.1           0.080
9       10176.60       4500.0      10.0                1.9           0.060

   Block  Process  Flange_Total  Platform_Area^2  Platform_Area Topside_LWT  \
0   99.0     90.0         784.0     3.728066e+08                135157400.0
1  112.0     91.0         981.0     3.253550e+08                360752000.0
2  103.0     91.0         771.0     4.008645e+08                130140400.0
3  119.0     89.0         918.0     3.187225e+08                258865600.0
4   90.0     88.0        1076.0     3.930306e+08                634400000.0
5  120.0     88.0        1109.0     3.461460e+08                697278190.0
6  106.0     92.0         911.0     3.937443e+08                277801860.0
7  108.0     89.0         937.0     2.228153e+08                238832000.0
8  106.0     89.0         882.0     1.562050e+08                149978400.0
9   85.0     89.0         708.0     1.035632e+08                 45794700.0

        ...          Block^3  Block^2 Process  Block^2 Flange_Total  \
0       ...         970299.0         882090.0             7683984.0
1       ...        1404928.0        1141504.0            12305664.0
2       ...        1092727.0         965419.0             8179539.0
3       ...        1685159.0        1260329.0            12999798.0
4       ...         729000.0         712800.0             8715600.0
5       ...        1728000.0        1267200.0            15969600.0
6       ...        1191016.0        1033712.0            10235996.0
7       ...        1259712.0        1038096.0            10929168.0
8       ...        1191016.0        1000004.0             9910152.0
9       ...         614125.0         643025.0             5115300.0

   Block Process^2  Block Process Flange_Total  Block Flange_Total^2  \
0         801900.0                   6985440.0            60850944.0
1         927472.0                   9998352.0           107784432.0
2         852943.0                   7226583.0            61227423.0
3         942599.0                   9722538.0           100284156.0
4         696960.0                   8521920.0           104199840.0
5         929280.0                  11711040.0           147585720.0
6         897184.0                   8884072.0            87971626.0
7         855468.0                   9006444.0            94820652.0
8         839626.0                   8320788.0            82459944.0
9         673285.0                   5356020.0            42607440.0

   Process^3  Process^2 Flange_Total  Process Flange_Total^2  Flange_Total^3
0   729000.0               6350400.0              55319040.0    4.818903e+08
1   753571.0               8123661.0              87574851.0    9.440761e+08
2   753571.0               6384651.0              54094131.0    4.583140e+08
3   704969.0               7271478.0              75002436.0    7.736206e+08
4   681472.0               8332544.0             101884288.0    1.245767e+09
5   681472.0               8588096.0             108229528.0    1.363938e+09
6   778688.0               7710704.0              76352732.0    7.560580e+08
7   704969.0               7421977.0              78139241.0    8.226570e+08
8   704969.0               6986322.0              69235236.0    6.861290e+08
9   704969.0               5608068.0              44612496.0    3.548949e+08

[10 rows x 164 columns]

In [63]:
print(polynomial_features.powers_)

[[1 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 2 1]
 [0 0 0 ... 0 1 2]
 [0 0 0 ... 0 0 3]]

In [64]:
print(poly_regressor.coef_)
print(poly_regressor.intercept_)

[[-3.94959634e-16  3.92275724e-15  9.78905292e-19  1.05394090e-18
  -1.78360173e-19  2.53522529e-17  3.91863803e-18  1.82247608e-16
  -9.48413175e-12  1.01325531e-11 -4.70473987e-14  1.62017110e-14
  -3.47790933e-15  5.64359006e-14  3.12365765e-14  8.73210849e-13
   3.76463832e-12  1.50876206e-14  3.52294216e-14 -4.05073833e-15
   4.63222954e-13  4.43963486e-13  3.00110293e-12 -4.48920035e-17
   2.22126838e-17 -4.31484226e-18  2.33320196e-16  1.66418284e-16
   2.02727860e-15  6.47163121e-18 -5.80338933e-19  1.62708619e-16
   1.07570267e-16  1.45653939e-15 -3.50301055e-20 -2.06891784e-17
  -1.58211224e-17 -1.77087307e-16  4.27347976e-15  2.69443948e-15
   3.46047013e-14  7.02175200e-16  2.03167622e-14  2.53946595e-13
   6.30338562e-11 -1.81840251e-10 -1.35485959e-09  2.74577047e-10
  -6.43519629e-11 -2.74469221e-09  2.65217098e-10 -1.26335854e-09
   1.10699169e-10 -4.66115429e-10  5.19397074e-10 -7.79146298e-11
   8.56173345e-10  2.58187062e-09  4.14238762e-09 -2.14336001e-12
   2.58060642e-13 -8.45307601e-14 -5.91213340e-12 -2.83237028e-12
  -3.23945415e-11  1.07805994e-13 -1.11046990e-14  1.97956942e-12
   1.68389538e-12  2.02406933e-11 -6.59403108e-16 -4.20816783e-13
  -3.08372448e-13 -3.52025710e-12  5.03837620e-12  1.24649992e-11
   1.24209395e-10  8.75934069e-12  1.48240300e-10  1.24745470e-09
   2.92479447e-11 -3.54611021e-10  6.63311654e-10 -8.59579098e-11
   1.71543881e-09  2.35953218e-09 -3.85659924e-09 -8.06794807e-13
   5.70748682e-13 -9.18616054e-14  1.81966045e-12  3.27747501e-12
   4.30851749e-12  1.75720611e-13 -1.11705585e-14  4.00391517e-12
   3.45001559e-12  3.40860208e-11 -7.69222240e-16 -4.66310628e-13
  -3.57598128e-13 -4.06511470e-12  4.81358778e-11  5.18074284e-11
   3.48793378e-10  4.81132236e-11  3.61917631e-10  2.05455752e-09
  -2.51258928e-15  3.05484167e-16 -1.02428701e-16 -5.09805442e-15
  -2.36425706e-15 -3.36647178e-14  1.28676592e-16 -1.31363704e-17
   2.68304524e-15  2.26010267e-15  2.54340948e-14 -8.43832118e-19
  -5.07435261e-16 -3.82262567e-16 -4.28446979e-15  2.63161032e-14
   2.96729133e-14  2.72597317e-13  2.19783842e-14  2.63516094e-13
   2.16565202e-12  2.92293429e-17 -1.73463758e-18  7.98789372e-16
   6.23579463e-16  7.37771299e-15 -1.20842403e-19 -6.68812113e-17
  -5.12873986e-17 -5.56338344e-16  2.04256745e-14  1.60372504e-14
   1.87523975e-13  1.08317933e-14  1.43812965e-13  1.64219416e-12
  -6.46044886e-21 -4.26069382e-18 -3.11656442e-18 -3.54632064e-17
  -2.46744879e-15 -1.83249949e-15 -2.07363052e-14 -1.40065718e-15
  -1.56588332e-14 -1.78439247e-13  5.23875969e-13  4.29480821e-13
   4.48787840e-12  2.79356025e-13  3.53754387e-12  3.57218723e-11
   9.43678025e-14  2.17838832e-12  2.68150408e-11  2.60163593e-10]]
[8.20522259]

In [32]:
x_flange_test = pd.read_csv('data/flange_test.csv')
x_flange_test

,Platform_Area,Topside_LWT,Lifetime,Shipbuilding_Time,Oil_Production,Block,Process,Flange_Total
0,15740.7,16234,19,2.8,0.13,94,94,899
1,15911.8,16398,17,2.8,0.12,113,95,934
2,16596.2,17710,19,2.4,0.14,108,93,943

In [36]:
y_flange_linear = linear_regressor.predict(x_flange_test)
y_flange_poly = pipeline.predict(x_flange_test)

In [34]:
y_flange_linear

array([[31.55449847],
       [33.33852348],
       [25.26419882]])

In [38]:
y_flange_poly

array([[40.29552416],
       [32.02667375],
       [27.88092604]])